#!/bin/bash

# store uncommited changes
git stash

# make sure we are in develop branch
git checkout develop

# build the latest changes
site rebuild

# make sure local repo is up to date
# git fetch --all

# go to main branch - create one if it doesn't exist, otherwise reset the
# existing main branch
git checkout -B main --track origin/main

# commit
git add -A
git commit -m "Publish"

# push
git push --set-upstream origin main

# restore state of repo
git checkout develop
git stash pop
